<a href="https://colab.research.google.com/github/jarodchristiansen/PythonProjects/blob/master/4th_SkLearn_(Standardization).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install --upgrade -q gspread
!pip install gspread-dataframe

Requirement already satisfied: gspread-dataframe in /usr/local/lib/python3.6/dist-packages (3.0.3)
Requirement already satisfied: gspread>=3.0.0 in /usr/local/lib/python3.6/dist-packages (from gspread-dataframe) (3.2.0)
Requirement already satisfied: pandas>=0.14.0 in /usr/local/lib/python3.6/dist-packages (from gspread-dataframe) (0.25.3)
Requirement already satisfied: requests>=2.2.1 in /usr/local/lib/python3.6/dist-packages (from gspread>=3.0.0->gspread-dataframe) (2.21.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.14.0->gspread-dataframe) (2018.9)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.14.0->gspread-dataframe) (1.17.5)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.14.0->gspread-dataframe) (2.6.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.2.1->gspread>=3.0.0->gspread-dataframe) (2019.11.28)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests>=2.2.1->gspread>=3.0.0->gspread-dataframe) (2.8)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.2.1->gspread>=3.0.0->gspread-dataframe) (1.24.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.2.1->gspread>=3.0.0->gspread-dataframe) (3.0.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/dist-packages (from python-dateutil>=2.6.1->pandas>=0.14.0->gspread-dataframe) (1.12.0)

These requirements should normally be satisfied, they are dependencies for gspread to pull the dataframe

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn
seaborn.set()
import gspread
from gspread_dataframe import get_as_dataframe, set_with_dataframe

from sklearn.linear_model import LinearRegression

COL_RAND = "Rand 1,2,3"

Import necessary libraries to create dataframe, regression, and formatting of regression (plotting) Gspread creates dataframe from sheets file

In [ ]:
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
gc = gspread.authorize(GoogleCredentials.get_application_default())

This will create authorization through google sheets (follow link that appears and copy authorization code)

In [ ]:
sheet1 = gc.open_by_url('https://docs.google.com/spreadsheets/d/1Kljn-lQAhMrjyuf_3JEPQ-lU6Am9dWZSdJDEVOV8UwM/edit#gid=0')

sheet1 is entire csv file URL is sheets file URL

In [ ]:
ws = sheet1.worksheet('Data')

This is the tab in csv file

In [ ]:
data = get_as_dataframe(ws)

titles the dataframe extracted from sheets file

In [ ]:
data

        SAT  Rand 1,2,3   GPA  ...  Unnamed: 23  Unnamed: 24  Unnamed: 25
0    1634.0         2.0  3.42  ...          NaN          NaN          NaN
1    1663.0         3.0  3.20  ...          NaN          NaN          NaN
2    1664.0         3.0  2.52  ...          NaN          NaN          NaN
3    1670.0         1.0  2.91  ...          NaN          NaN          NaN
4    1674.0         2.0  3.17  ...          NaN          NaN          NaN
..      ...         ...   ...  ...          ...          ...          ...
994     NaN         NaN   NaN  ...          NaN          NaN          NaN
995     NaN         NaN   NaN  ...          NaN          NaN          NaN
996     NaN         NaN   NaN  ...          NaN          NaN          NaN
997     NaN         NaN   NaN  ...          NaN          NaN          NaN
998     NaN         NaN   NaN  ...          NaN          NaN          NaN

[999 rows x 26 columns]

This is calling the dataframe and representing from Pandas. NaN cells are empty values

In [ ]:
data = data.dropna(axis=0, how='all')

dropna() is a methodfrom Pandas to remove NaN cells, axis=0 is rows how is any or all, inplace True removes from the dataframe

In [ ]:
data = data.dropna(axis=1, how='all')

dropna() is a methodfrom Pandas to remove NaN cells, axis=1 is columns how is any or all, inplace True removes from the dataframe

In [ ]:
data

       SAT  Rand 1,2,3   GPA
0   1634.0         2.0  3.42
1   1663.0         3.0  3.20
2   1664.0         3.0  2.52
3   1670.0         1.0  2.91
4   1674.0         2.0  3.17
..     ...         ...   ...
79  2020.0         1.0  3.28
80  2020.0         2.0  3.65
81  2021.0         3.0  3.61
82  2041.0         3.0  3.51
83  2050.0         2.0  3.81

[84 rows x 3 columns]

calls the corrected dataframe

In [ ]:
x = data[['SAT', COL_RAND]]
y = data ['GPA']

sets the target (y) and feature (x)

In [ ]:
from sklearn.preprocessing import StandardScaler

Imports scaler from sklearn to perform standardizing

In [ ]:
scaler = StandardScaler()

creates an Object named scaler to call the StandardScaler (standardization)(Feature Scaling) function. Note that this object is empty upon the declaration hence the ()

In [ ]:
scaler.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

This is processing the equation to find the mean and standard deviation. This will then be used to find the standardized feature weight. 

standardized variables

Subtract the mean, μ, from the value you want to convert, X.
Divide the result from Step 1 by the standard deviation, σ.

In [ ]:
x_scaled = scaler.transform(x)

Transform called on the scaler object finds the standardized weight for each input. This is assigning it to the variable  "x_scaled"

In [ ]:
x_scaled

array([[-2.03330517, -0.07002087],
       [-1.75420834,  1.10632974],
       [-1.74458431,  1.10632974],
       [-1.68684014, -1.24637147],
       [-1.64834403, -0.07002087],
       [-1.54247971,  1.10632974],
       [-1.52323165, -1.24637147],
       [-1.46548748, -0.07002087],
       [-1.37887123, -1.24637147],
       [-1.28263094,  1.10632974],
       [-1.26338288, -1.24637147],
       [-1.18639066,  1.10632974],
       [-1.10939843, -0.07002087],
       [-1.06127829,  1.10632974],
       [-1.06127829, -1.24637147],
       [-0.86879772,  1.10632974],
       [-0.82067757,  1.10632974],
       [-0.81105355,  1.10632974],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.73406132, -1.24637147],
       [-0.6955652 , -0.07002087],
       [-0.67631715, -0.07002087],
       [-0.67631715, -1.24637147],
       [-0.65706909,  1.10632974],
       [-0.64744506, -1.24637147],
       [-0.61857297, -0.07002087],
       [-0.57045283,  1.10632974],
       [-0.5608288 , -1.24637147],
       [-0.51270866, -0.07002087],
       [-0.4934606 , -0.07002087],
       [-0.41646838,  1.10632974],
       [-0.35872421,  1.10632974],
       [-0.35872421,  1.10632974],
       [-0.33947615, -1.24637147],
       [-0.23361183,  1.10632974],
       [-0.20473975, -0.07002087],
       [-0.18549169, -1.24637147],
       [-0.13737155, -0.07002087],
       [-0.12774752, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.02188321,  1.10632974],
       [ 0.03586096, -0.07002087],
       [ 0.04548499,  1.10632974],
       [ 0.04548499, -1.24637147],
       [ 0.04548499,  1.10632974],
       [ 0.09360513,  1.10632974],
       [ 0.09360513, -1.24637147],
       [ 0.11285319, -1.24637147],
       [ 0.15134931, -0.07002087],
       [ 0.18984542,  1.10632974],
       [ 0.25721362, -0.07002087],
       [ 0.32458182, -1.24637147],
       [ 0.33420585, -0.07002087],
       [ 0.40157405, -1.24637147],
       [ 0.44007016, -0.07002087],
       [ 0.45931822,  1.10632974],
       [ 0.45931822, -1.24637147],
       [ 0.59405462, -0.07002087],
       [ 0.76728713, -0.07002087],
       [ 0.8250313 ,  1.10632974],
       [ 0.84427936,  1.10632974],
       [ 0.85390339, -1.24637147],
       [ 0.85390339, -0.07002087],
       [ 0.85390339,  1.10632974],
       [ 0.87315144,  1.10632974],
       [ 1.03675993, -1.24637147],
       [ 1.04638396,  1.10632974],
       [ 1.06563201, -1.24637147],
       [ 1.12337618, -1.24637147],
       [ 1.14262424, -1.24637147],
       [ 1.1618723 ,  1.10632974],
       [ 1.23886453, -1.24637147],
       [ 1.24848856, -1.24637147],
       [ 1.28698467,  1.10632974],
       [ 1.3639769 ,  1.10632974],
       [ 1.39284898, -1.24637147],
       [ 1.46021718, -1.24637147],
       [ 1.6334497 ,  1.10632974],
       [ 1.68156984, -1.24637147],
       [ 1.68156984, -0.07002087],
       [ 1.69119387,  1.10632974],
       [ 1.88367444,  1.10632974],
       [ 1.97029069, -0.07002087]])

This is displaying the standardized version of each input. Further analysis can now be done.

In [ ]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [ ]:
reg.intercept_

3.3302380952380948

In [ ]:
reg_summary = pd.DataFrame([['Bias'], ['SAT'], [COL_RAND]], columns= ['Features'])

In [ ]:
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [ ]:
reg_summary

     Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

In [ ]:
new_data = pd.DataFrame(data=[[1700,2], [1800,1]], columns=['SAT', COL_RAND])
new_data

    SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [ ]:
reg.predict(new_data)

array([295.39979563, 312.58821497])